### ISSUE TITLE
a problem of robox scrips

### ISSUE THREAD

**Issue by GitSoftwareNow** [lag-linaro/robox#1]
when I run the robox scripts ,it reports that DKMS source tree has contained anbox-linux-1
I tried run dkms remove -m anbox-linux -v 1 --all and run robox again but it  reports that DKMS source tree has contained anbox-linux-1 still on my system

**Comment by lag-linaro** [comment]
FYI: These scripts haven't been run for 2-3 years.  Bitrot is a real possibility. 

Here are my notes about DKMS:

```
- sudo apt-get install dkms
- dkms status
- sudo dkms remove anbox-ashmem/1 --all
- sudo dkms install <path_to_build_dir>/ashmem
- sudo modprobe binder_linux num_devices=256
```

Good luck.
