### ISSUE TITLE
The container can not run

### ISSUE THREAD

**Issue by GitSoftwareNow** [lag-linaro/robox#5]
here are some debug infomations
./robox -v -d start 1
1: Attempting to start instance instance1
1: /dev/binder1 appears to be present
1: /dev/ashmem appears to be present
1: Ensuring /dev/binder1 and /dev/ashmem are useable
1: STARTING Frame Buffer
1: Xvfb :1 -ac -screen 0 1024x768x24
1: STARTING Session Manager
1: anbox session-manager --run-multiple=instance1 --standalone --experimental --single-window --gles-driver=translator
1: CREATING network configuration (using 172.17.0.2)
1: Ensuring all sockets are useable
1: STARTING Docker container
1: Not all sockets are present - ZZzzz!
1: docker run -d -it --cap-add=SYS_ADMIN --cap-add=NET_ADMIN --cap-add=SYS_MODULE --cap-add=SYS_NICE --cap-add=SYS_TIME --cap-add=SYS_TTY_CONFIG --cap-add=NET_BROADCAST --cap-add=IPC_LOCK --cap-add=SYS_RESOURCE --security-opt=apparmor=unconfined --security-opt=seccomp=robox.json --name instance1 -e PATH=/system/bin:/system/xbin --device=/dev/binder1:/dev/binder:rwm --device=/dev/ashmem:/dev/ashmem:rwm --device=/dev/fuse:/dev/fuse:rwm --volume=/run/user/0/anbox/instance1/sockets/qemu_pipe:/dev/qemu_pipe --volume=/run/user/0/anbox/instance1/sockets/anbox_audio:/dev/anbox_audio:rw --volume=/run/user/0/anbox/instance1/sockets/anbox_bridge:/dev/anbox_bridge:rw --volume=/run/user/0/anbox/instance1/input/event0:/dev/input/event0:rw --volume=/run/user/0/anbox/instance1/input/event1:/dev/input/event1:rw --volume=/root/anbox-data/instance1/cache:/cache:rw --volume=/root/anbox-data/instance1/data:/data:rw android /anbox-init.sh
1: STARTING VNC Server
1: x11vnc -display :1 -N -forever -shared -reopen -passwd robox14816 -desktop instance1 -bg
1: PASSWORD=robox14816

**Comment by lag-linaro** [comment]
This is the 5th Issue you have opened.

My guess is that, as you've reached this far, you have resolved the other Issues.

Taking into consideration that you are not answering my replies to your Issues, I am closing them.
